import Prod01Jpg from '../assets/prod-01.jpg';
import Prod02Jpg from '../assets/prod-02.jpg';
import Prod03Jpg from '../assets/prod-03.jpg';
import Prod04Jpg from '../assets/prod-01.jpg';
import Prod05Jpg from '../assets/prod-01.jpg';
import Prod06Jpg from '../assets/prod-01.jpg';
import Prod07Jpg from '../assets/prod-01.jpg';
import Prod08Jpg from '../assets/prod-01.jpg';

export interface IProduct {
    id: number,
    title: string,
    description: String,
    points: number,
    image: string,
    nuevo: boolean,
    oferta: boolean,
    descuento: boolean,
    tarjeta: boolean,
}

export const productList: Array<IProduct> = [
    // {
    //     id: 12,
    //     title: 'Juego PS4 Fornite',
    //     description: 'Juego de Play 4, el mejor del año',
    //     points: 15000,
    //     image: Prod01Jpg,
    // },
    // {
    //     id: 13,
    //     title: 'Han Solo Una Historia de Star Wars Blu-ra',
    //     description: 'Juego de Play 4, el mejor del año',
    //     points: 25000,
    //     image: Prod02Jpg,
    // },
    // {
    //     id: 14,
    //     title: 'Juego PS4 Fornite',
    //     description: 'Juego de Play 4, el mejor del año',
    //     points: 15000,
    //     image: Prod03Jpg,
    // },
    // {
    //     id: 15,
    //     title: 'Juego PS4 Fornite',
    //     description: 'Juego de Play 4, el mejor del año',
    //     points: 15000,
    //     image: Prod04Jpg,
    // },
    {
        id: 12,
        title: 'Juego PS4 Fornite',
        description: 'Juego de Play 4, el mejor del año',
        points: 15000,
        image: Prod01Jpg,
        nuevo: true,
        oferta: false,
        descuento: true,
        tarjeta: false,
    },
    {
        id: 13,
        title: 'Han Solo Una Historia de Star Wars Blu-ra',
        description: 'Juego de Play 4, el mejor del año',
        points: 25000,
        image: Prod02Jpg,
        nuevo: true,
        oferta: false,
        descuento: true,
        tarjeta: false,
    },
    {
        id: 14,
        title: 'Juego PS4 Fornite',
        description: 'Juego de Play 4, el mejor del año',
        points: 15000,
        image: Prod03Jpg,
        nuevo: true,
        oferta: false,
        descuento: false,
        tarjeta: false,
    },
    {
        id: 15,
        title: 'Juego PS4 Fornite',
        description: 'Juego de Play 4, el mejor del año',
        points: 15000,
        image: Prod04Jpg,
        nuevo: false,
        oferta: false,
        descuento: true,
        tarjeta: false,
    },
    {
        id: 12,
        title: 'Juego PS4 Fornite',
        description: 'Juego de Play 4, el mejor del año',
        points: 15000,
        image: Prod01Jpg,
        nuevo: true,
        oferta: true,
        descuento: true,
        tarjeta: false,
    },
    {
        id: 13,
        title: 'Han Solo Una Historia de Star Wars Blu-ra',
        description: 'Juego de Play 4, el mejor del año',
        points: 25000,
        image: Prod02Jpg,
        nuevo: false,
        oferta: false,
        descuento: true,
        tarjeta: true,
    },
    {
        id: 14,
        title: 'Juego PS4 Fornite',
        description: 'Juego de Play 4, el mejor del año',
        points: 15000,
        image: Prod03Jpg,
        nuevo: true,
        oferta: false,
        descuento: false,
        tarjeta: false,
    },
    {
        id: 15,
        title: 'Juego PS4 Fornite',
        description: 'Juego de Play 4, el mejor del año',
        points: 15000,
        image: Prod04Jpg,
        nuevo: false,
        oferta: false,
        descuento: false,
        tarjeta: false,
    },
];